// SET ARRAY CHAMPION LIST
const championList = [ { name: "Aatrox", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Aatrox.png?v=v8" },
{ name: "Ahri", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ahri.png?v=v8" },
{ name: "Akali", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Akali.png?v=v8" },
{ name: "Alistar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Alistar.png?v=v8" },
{ name: "Amumu", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Amumu.png?v=v8" },
{ name: "Anivia", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Anivia.png?v=v8" },
{ name: "Annie", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Annie.png?v=v8" },
{ name: "Aphelios", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Aphelios.png?v=v8" },
{ name: "Ashe", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ashe.png?v=v8" },
{ name: "AurelionSol", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/AurelionSol.png?v=v8" },
{ name: "Azir", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Azir.png?v=v8" },
{ name: "Bard", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Bard.png?v=v8" },
{ name: "Blitzcrank", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Blitzcrank.png?v=v8" },
{ name: "Brand", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Brand.png?v=v8" },
{ name: "Braum", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Braum.png?v=v8" },
{ name: "Caitlyn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Caitlyn.png?v=v8" },
{ name: "Camille", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Camille.png?v=v8" },
{ name: "Cassiopeia", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Cassiopeia.png?v=v8" },
{ name: "Chogath", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Chogath.png?v=v8" },
{ name: "Corki", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Corki.png?v=v8" },
{ name: "Darius", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Darius.png?v=v8" },
{ name: "Diana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Diana.png?v=v8" },
{ name: "DrMundo", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/DrMundo.png?v=v8" },
{ name: "Draven", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Draven.png?v=v8" },
{ name: "Ekko", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ekko.png?v=v8" },
{ name: "Elise", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Elise.png?v=v8" },
{ name: "Evelynn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Evelynn.png?v=v8" },
{ name: "Ezreal", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ezreal.png?v=v8" },
{ name: "Fiddlesticks", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Fiddlesticks.png?v=v8" },
{ name: "Fiora", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Fiora.png?v=v8" },
{ name: "Fizz", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Fizz.png?v=v8" },
{ name: "Galio", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Galio.png?v=v8" },
{ name: "Gangplank", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Gangplank.png?v=v8" },
{ name: "Garen", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Garen.png?v=v8" },
{ name: "Gnar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Gnar.png?v=v8" },
{ name: "Gragas", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Gragas.png?v=v8" },
{ name: "Graves", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Graves.png?v=v8" },
{ name: "Hecarim", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Hecarim.png?v=v8" },
{ name: "Heimerdinger", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Heimerdinger.png?v=v8" },
{ name: "Illaoi", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Illaoi.png?v=v8" },
{ name: "Irelia", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Irelia.png?v=v8" },
{ name: "Ivern", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ivern.png?v=v8" },
{ name: "Janna", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Janna.png?v=v8" },
{ name: "JarvanIV", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/JarvanIV.png?v=v8" },
{ name: "Jax", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jax.png?v=v8" },
{ name: "Jayce", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jayce.png?v=v8" },
{ name: "Jhin", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jhin.png?v=v8" },
{ name: "Jinx", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Jinx.png?v=v8" },
{ name: "Kaisa", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kaisa.png?v=v8" },
{ name: "Kalista", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kalista.png?v=v8" },
{ name: "Karma", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Karma.png?v=v8" },
{ name: "Karthus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Karthus.png?v=v8" },
{ name: "Kassadin", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kassadin.png?v=v8" },
{ name: "Katarina", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Katarina.png?v=v8" },
{ name: "Kayle", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kayle.png?v=v8" },
{ name: "Kayn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kayn.png?v=v8" },
{ name: "Kennen", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kennen.png?v=v8" },
{ name: "Khazix", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Khazix.png?v=v8" },
{ name: "Kindred", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kindred.png?v=v8" },
{ name: "Kled", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Kled.png?v=v8" },
{ name: "KogMaw", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/KogMaw.png?v=v8" },
{ name: "Leblanc", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Leblanc.png?v=v8" },
{ name: "LeeSin", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/LeeSin.png?v=v8" },
{ name: "Leona", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Leona.png?v=v8" },
{ name: "Lillia", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lillia.png?v=v8" },
{ name: "Lissandra", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lissandra.png?v=v8" },
{ name: "Lucian", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lucian.png?v=v8" },
{ name: "Lulu", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lulu.png?v=v8" },
{ name: "Lux", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Lux.png?v=v8" },
{ name: "Malphite", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Malphite.png?v=v8" },
{ name: "Malzahar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Malzahar.png?v=v8" },
{ name: "Maokai", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Maokai.png?v=v8" },
{ name: "MasterYi", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/MasterYi.png?v=v8" },
{ name: "MissFortune", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/MissFortune.png?v=v8" },
{ name: "Mordekaiser", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Mordekaiser.png?v=v8" },
{ name: "Morgana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Morgana.png?v=v8" },
{ name: "Nami", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nami.png?v=v8" },
{ name: "Nasus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nasus.png?v=v8" },
{ name: "Nautilus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nautilus.png?v=v8" },
{ name: "Neeko", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Neeko.png?v=v8" },
{ name: "Nidalee", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nidalee.png?v=v8" },
{ name: "Nocturne", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nocturne.png?v=v8" },
{ name: "Nunu", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Nunu.png?v=v8" },
{ name: "Olaf", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Olaf.png?v=v8" },
{ name: "Orianna", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Orianna.png?v=v8" },
{ name: "Ornn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ornn.png?v=v8" },
{ name: "Pantheon", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Pantheon.png?v=v8" },
{ name: "Poppy", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Poppy.png?v=v8" },
{ name: "Pyke", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Pyke.png?v=v8" },
{ name: "Qiyana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Qiyana.png?v=v8" },
{ name: "Quinn", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Quinn.png?v=v8" },
{ name: "Rakan", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Rakan.png?v=v8" },
{ name: "Rammus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Rammus.png?v=v8" },
{ name: "RekSai", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/RekSai.png?v=v8" },
{ name: "Renekton", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Renekton.png?v=v8" },
{ name: "Rengar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Rengar.png?v=v8" },
{ name: "Riven", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Riven.png?v=v8" },
{ name: "Rumble", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Rumble.png?v=v8" },
{ name: "Ryze", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ryze.png?v=v8" },
{ name: "Sejuani", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sejuani.png?v=v8" },
{ name: "Senna", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Senna.png?v=v8" },
{ name: "Sett", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sett.png?v=v8" },
{ name: "Shaco", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Shaco.png?v=v8" },
{ name: "Shen", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Shen.png?v=v8" },
{ name: "Shyvana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Shyvana.png?v=v8" },
{ name: "Singed", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Singed.png?v=v8" },
{ name: "Sion", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sion.png?v=v8" },
{ name: "Sivir", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sivir.png?v=v8" },
{ name: "Skarner", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Skarner.png?v=v8" },
{ name: "Sona", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sona.png?v=v8" },
{ name: "Soraka", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Soraka.png?v=v8" },
{ name: "Swain", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Swain.png?v=v8" },
{ name: "Sylas", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Sylas.png?v=v8" },
{ name: "Syndra", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Syndra.png?v=v8" },
{ name: "TahmKench", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/TahmKench.png?v=v8" },
{ name: "Taliyah", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Taliyah.png?v=v8" },
{ name: "Talon", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Talon.png?v=v8" },
{ name: "Taric", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Taric.png?v=v8" },
{ name: "Teemo", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Teemo.png?v=v8" },
{ name: "Thresh", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Thresh.png?v=v8" },
{ name: "Tristana", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Tristana.png?v=v8" },
{ name: "Trundle", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Trundle.png?v=v8" },
{ name: "Tryndamere", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Tryndamere.png?v=v8" },
{ name: "TwistedFate", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/TwistedFate.png?v=v8" },
{ name: "Twitch", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Twitch.png?v=v8" },
{ name: "Udyr", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Udyr.png?v=v8" },
{ name: "Urgot", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Urgot.png?v=v8" },
{ name: "Varus", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Varus.png?v=v8" },
{ name: "Vayne", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Vayne.png?v=v8" },
{ name: "Veigar", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Veigar.png?v=v8" },
{ name: "Velkoz", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Velkoz.png?v=v8" },
{ name: "Vi", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Vi.png?v=v8" },
{ name: "Viktor", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Viktor.png?v=v8" },
{ name: "Vladimir", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Vladimir.png?v=v8" },
{ name: "Volibear", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Volibear.png?v=v8" },
{ name: "Warwick", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Warwick.png?v=v8" },
{ name: "Wukong", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/MonkeyKing.png?v=v8" },
{ name: "Xayah", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Xayah.png?v=v8" },
{ name: "Xerath", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Xerath.png?v=v8" },
{ name: "XinZhao", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/XinZhao.png?v=v8" },
{ name: "Yasuo", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Yasuo.png?v=v8" },
{ name: "Yone", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Yone.png?v=v8" },
{ name: "Yorick", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Yorick.png?v=v8" },
{ name: "Yuumi", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Yuumi.png?v=v8" },
{ name: "Zac", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zac.png?v=v8" },
{ name: "Zed", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zed.png?v=v8" },
{ name: "Ziggs", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Ziggs.png?v=v8" },
{ name: "Zilean", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zilean.png?v=v8" },
{ name: "Zoe", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zoe.png?v=v8" },
{ name: "Zyra", img: "https://www.masterypoints.com/assets/img/lol/champion_icons/Zyra.png?v=v8" },
];

// SET ARRAY TALKS
const talkList = [
                    { msg: "Prazer em conhecer você!" },
                    { msg: "Eles não vão gostar nada disso." },
                    { msg: "Acabe com eles, Pix!" },
                    { msg: "Vamos usar TODAS as cores!" },
                    { msg: "Muito alto... Muito muito alto." },
                    { msg: "Uma risadinha deve resolver o problema." },
                    { msg: "Vou em um pé e volto no outro." },
                    { msg: "Só uma pitadinha..." },
                    { msg: "É, tem um gosto meio roxo!" },
                    { msg: "Conseguirá ver melhor com os olhos fechados" },
                    { msg: "Ai... Tô tonta!" },
                    { msg: "Orvalho intrometido!" },
                    { msg: "Nunca olhe diretamente para uma tulipa..." },
                    { msg: "Conheço esse esquilo de algum lugar." },
                    { msg: "Que tal uma giradinha? Whoa, whoa whoa ah, ihaha!" },
                    { msg: "Precisamos pensar direitinho! Hmm... hmmhmm... Ah! Entendi" },
                    { msg: "Vamos lá, vamos dançar! Há!" },
                    { msg: "Vamos dar mais uma volta! Há!" },
                    { msg: "Essa batalha será minha obra prima." },
                    { msg: "Retalhe a coragem deles." },
                    { msg: "A cada abate a vitória se aproxima." },
                    { msg: "Não haverá retirada." },
                    { msg: "Lute ou seja esquecido." },
                    { msg: "Honra não irá salvá-los." },
                    { msg: "Quebre e caia." },
                    { msg: "Ensine-os a nos temer." },
                    { msg: "Agora viramos o jogo!" },
                    { msg: "Plante as sementes da discórdia" },
                    { msg: "Ruja contra a luz que morre e não fulgura." },
                    { msg: "Violência é elegância." },
                    { msg: "A dor é temporária, a vitória é eterna!" },
                    { msg: "Paz é a maior das mentiras." },
                    { msg: "A guerra revela o que há dentro de nós." },
                    { msg: "Supere a fragilidade de sua forma." },
                    { msg: "Eles lhe saudarão como heróis." },
                    { msg: "Verdadeiro guerreiros nascem em sangue!" },
                    { msg: "Sou tão atemporal quanto a guerra." },
                    { msg: "Deixe o medo se tornar fúria!" },
                    { msg: "Eu sei o que espreita no coração dos homens." },
                    { msg: "Hesitação é morte." },
                    { msg: "Ninguém me entende! Me chamam até de açougueiro de quinta." },
                    { msg: "Isso não é um mero massacre. É a minha obra magistral!" },
                    { msg: "Lute e seja lembrado como um herói, ou morra e seja lembrado como um covarde." },
                    { msg: "Lute como um herói, ou morra como um covarde." },
                    { msg: "Lute e seja lembrado, ou morra e seja esquecido." },
                    { msg: "Morra com medo em seu coração, ou vença com sangue em suas mãos." },
                    { msg: "Mesmo aqueles que nada tem podem dar suas vidas." },
                    { msg: "Falas não organizadas por evento que as inicia. Grunhidos e sons individuais foram excluídos." },
                    { msg: "Isso não é pra pendurar na parede." },
                    { msg: "Espero que você saiba como usar isso." },
                    { msg: "Não aceito devoluções." },
                    { msg: "Se quiser uma arma, aqui está. Se quiser conversar, aqui está uma arma." },
                    { msg: "Usa isso direito, você não vai se arrepender." },
                    { msg: "Ornn testou, Ornn aprovou." },
                    { msg: "Isso não significa que somos amigos." },
                    { msg: "Um bom machado, derruba árvores. Um grande machado, derruba exércitos." },
                    { msg: "As armas que eu crio não tem nome, elas têm ambição." },
                    { msg: "Isso é um arma, sabe, pra lutar." },
                    { msg: "Você me parece merecer isso, não me decepcione." },
                    { msg: "Isso é o que bom significa." },
                    { msg: "É para empunhar, e não para brincar." },
                    { msg: "Também estava de olho nessa." },
                    { msg: "Não fiz nada, e você não comprou nada, tá?" },
                    { msg: "Já chega!" },
                    { msg: "Não se mova!" },
                    { msg: "Forjando nervos de aço!" },
                    { msg: "Vou te transformar em pó!" },
                    { msg: "Até a minha barba está com raiva!" },
                    { msg: "Tá na hora da bigorna!" },
                    { msg: "Segura minha cerveja!" },
                    { msg: "Que bela surra!" },
                    { msg: "É assim que se cria vergonha!" },
                    { msg: "Nariz, te apresento o martelo!" },
                    { msg: "Vai ser música pros meus ouvidos!" },
                    { msg: "Ahh, é relaxante dar uma surra." },
                    { msg: "Eu falo a língua da luta!" },
                    { msg: "Sou bem cabeça dura!" },
                    { msg: "Eu estava trabalhando!" },
                    { msg: "O trabalho é a recompensa!" },
                    { msg: "O martelo nunca falha." },
                    { msg: "Não gosto do formato daquilo." },
                    { msg: "Já que não conversamos, vamos lutar." },
                    { msg: "Sua espada precisa de um contrapeso." },
                    { msg: "Passa a cerveja, e ninguém se machuca." },
                    { msg: "Pare de construir, meu martelo é melhor." },
                    { msg: "Hehe, arrebentei pra valer!" },
                    { msg: "Vem fácil, vai fácil." },
                    { msg: "Destreza mortal, ha, francamente." },
                    { msg: "Opa, encontrei um defeito." },
                    { msg: "Um espirro forte teria causado o mesmo estrago." },
                    { msg: "Acabamento ruim." },
                    { msg: "Demolido, moleza." },
                    { msg: "Mal encostei nisso." },
                    { msg: "Hm, sabor cereja, nada mal." },
                    { msg: "Ajuda a manter a chama acesa." },
                    { msg: "Não sei o que tem nessa bebida, mas tá funcionando." },
                    { msg: "Hmm, notas frutadas de cereja." },
                    { msg: "Bom trabalho!" },
                    { msg: "Quebrei minha barba!" },
                    { msg: "Doran aprendeu comigo tudo o que sabe." },
                    { msg: "A melhor refeição é um rebanho mal passado, cerveja escura e cerejas." },
                    { msg: "Vou por aqui, não me siga, por favor." },
                    { msg: "Eu que fiz esse martelo, ficou tão bom que chamei de... martelo." },
                    { msg: "Vou por ali, parece tranquilo, e legal." },
                    { msg: "Meu nome é Ornn, já chega de apresentações." },
                    { msg: "Eu sou peludo e macio. Não me abrace." },
                    { msg: "Freljord é um lugar para se construir, lutar e comer. Lar, doce lar." },
                    { msg: "Se tudo acabar bem, nossos caminhos nunca mais irão se cruzar. Só que nunca acaba bem." },
                    { msg: "De nada." },
                    { msg: "Compre um livro de piadas e um palhaço." },
                    { msg: "Gosto ainda menos de você, não sabia que era possível." },
                    { msg: "Para." },
                    { msg: "É, acabou." },
                    { msg: "Trabalho concluído." },
                    { msg: "O prazer não foi meu." },
                    { msg: "Construção de caráter." },
                    { msg: "Bom, fazer o quê." },
                    { msg: "Martelei um prego!" },
                    { msg: "Aqui, não!" },
                    { msg: "Fuça isso aqui, negativo." },
                    { msg: "Haha, destruí legal." },
                    { msg: "Pronto, consertei pra você." },
                    { msg: "O segredo é avisar primeiro." },
                    { msg: "Já estava assim quando eu cheguei." },
                    { msg: "Ahn, estamos prontos Ornn, estaremos bem atrás de você! Aham!" },
                    { msg: "Isso, deixem tudo pra eu fazer, pra variar." },
                    { msg: "Bom trabalho pessoal." },
                    { msg: "Estou acostumado a me decepcionar assim." },
                    { msg: "Os humanos acertaram em algumas coisas, como cerveja, cerveja escura." },
                    { msg: "Quando os humanos se ajoelham, dificilmente se levantam." },
                    { msg: "Minha forja é meu lar." },
                    { msg: "Eu não preciso de companhia, só de uma parede, para evitar companhia." },
                    { msg: "Certa vez, fiz um arpão com uma montanha e uma árvore mística, foi um século esquisito." },
                    { msg: "Argh, tantas árvores descuidadas." },
                    { msg: "Trabalho duro é o maior prazer da vida." },
                    { msg: "Os outros deuses não me entendem, ha, melhor assim." },
                    { msg: "Sabe quando eu comi planta? Nunca." },
                    { msg: "Um dia longe da forja, é um dia jogado fora." },
                    { msg: "Meu trabalho fala o rugido das chamas e do tilintar do aço." },
                    { msg: "Vou fazer um machado que também é espada, e talvez uma colher." },
                    { msg: "Tudo fica melhor derretido, chumbo, ferro, bolo de chocolate." },
                    { msg: "Eu já tive seguidores, eles até que tentaram." },
                    { msg: "Que infantilidade preferir uma ferramenta só, meu martelo é meu favorito." },
                    { msg: "Sorte é o fracasso que falhou." },
                    { msg: "Gosto de ficar sozinho, menos acidentes de trabalho." },
                    { msg: "Eu só preciso de mim mesmo, e do martelo." },
                    { msg: "Em Freljord, os homens são forjados de sujeira e goblins, ou seja lá do que crianças são feitas!" },
                    { msg: "Ornn cria coisas, vá falar com Ornn. Ninguém nunca agradece." },
                    { msg: "Esse mundo tem potencial, mas precisa de umas marteladas." },
                    { msg: "Deuses não precisam de seguidores, seguidores precisam de deuses." },
                    { msg: "A solidão nunca me decepciona." },
                    { msg: "Granito noxiano, escolha respeitável." },
                    { msg: "Essas muretas dão pro gasto." },
                    { msg: "Não precisava das estátuas." },
                    { msg: "Cantaria de primeira." },
                    { msg: "A pedra está solta, depois eu conserto." },
                    { msg: "A arquitetura aqui não é, totalmente horrível." },
                    { msg: "Awn, esse rio precisa de uma barragem." },
                    { msg: "Eu não queria me refrescar, mas gosto disso." },
                    { msg: "Volibear criou o primeiro rio. Nem te conto como." },
                    { msg: "Acabei o trabalho, hora de ir pra casa!" },
                    { msg: "De volta ao trabalho." },
                    { msg: "Eu me diverti bem mais do que esperava!" },
                    { msg: "Problema resolvido." },
                    { msg: "Acenda forja!" },
                    { msg: "Ao combate!" },
                    { msg: "Vamos esquentar!" },
                    { msg: "Argh, todo mundo atrás de mim!" },
                    { msg: "Lutamos agora!" },
                    { msg: "Na hora de tomar martelada!" },
                    { msg: "Hm, deixa pra lá." },
                    { msg: "Mudei de ideia." },
                    { msg: "Não morri, foi a forja que sentiu saudade." },
                    { msg: "A fonte ainda tá seca." },
                    { msg: "Reacendi a velha fornalha." },
                    { msg: "Seja lá o que quiser a resposta é vá embora." },
                    { msg: "Não sei, não quero saber e tenho raiva de quem sabe." },
                    { msg: "Sua base é pra lá, vá se esconder." },
                    { msg: "Seu trabalho é não morrer." },
                    { msg: "Você se parece comigo jovem, bem menos impressionante." },
                    { msg: "Até que você não é totalmente idiota." },
                    { msg: "Trabalhar contigo é quase como trabalhar sozinho, quase!" },
                    { msg: "Você precisa saber algo sobre mim." },
                    { msg: "Quanta perda de tempo." },
                    { msg: "Argh, eu não me importo." },
                    { msg: "Tô indo, pare de encher!" },
                    { msg: "Você pediu minha ajuda!" },
                    { msg: "Manter posição!" },
                    { msg: "Aguarde!" },
                    { msg: "Parados!" },
                    { msg: "Calma!" },
                    { msg: "Meus chifres estão a caminho!" },
                    { msg: "Cada um de vocês me deve uma cerveja!" },
                    { msg: "A caminho!" },
                    { msg: "Meu lugar é onde a luta acontece!" },
                    { msg: "Um bom trabalhador é essencial." },
                    { msg: "Se o Volibear estiver ali, eu juro que...!" },
                    { msg: "Hora de mostrar os chifres pra eles!" },
                    { msg: "Método eficiente de viagem, aprovado." },
                    { msg: "Hm, isso é rápido, mas não deve fazer bem." },
                    { msg: "Prefiro andar mas, tudo bem." },
                    { msg: "Nóis se vê por aí!" },
                    { msg: "Vou chegar na surdina." },
                    { msg: "Adoro surpresas." },
                    { msg: "E lá vamos nós." },
                    { msg: "Feitiçaria demais, trabalho duro de menos!" },
                    { msg: "Humf, não sendo uma das minhas." },
                    { msg: "Construa de novo, só que do jeito certo." },
                    { msg: "É sério, eu só me apoiei nela." },
                    { msg: "É sempre a parte mágica que quebra." },
                    { msg: "Hã, já vi castelos de areia mais resistentes." },
                    { msg: "Argh, detesto surpresas." },
                    { msg: "Hm, é pra isso que serve, tá bom." },
                    { msg: "Você fica aqui." },
                    { msg: "Tá funcionando." },
                    { msg: "Hm, não sei o que acho dessa coisa, mas tudo bem." },
                    { msg: "(Ornn cheirando) Pelos chamuscados, sangue invejoso, meu irmão está por perto!" },
                    { msg: "O Volibear está próximo, busquem abrigo." },
                    { msg: "Não posso escolher meu irmão, apenas as armas para matá-lo!" },
                    { msg: "Sim, isso!"  },
                    { msg: "Sim, isso!"  },
                    { msg: "Você é um prego!"  },
                    { msg: "Disso eu gosto!"  },
                    { msg: "Gostou disso? Eu gostei!"  },
                    { msg: "E isso é pelos meus seguidores!"  },
                    { msg: "Não!"  },
                    { msg: "Consertei! Isso consertou tudo."  },
                    { msg: "Tá bom, já vou!"  },
                    { msg: "Chifres primeiro!"  },
                    { msg: "Não comecem sem mim!"  },
                    { msg: "Não gosto de você." },
                    { msg: "Destruído e derretido." },
                    { msg: "Desceu redondo." },
                    { msg: "Bom, gostei." },
                    { msg: "Hmm, é, morreu." },
                    { msg: "Todo mundo pronto?" },
                    { msg: "Eu não me importo mesmo." },
                    { msg: "Chumbo quente" },
                ]

